services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    restart: always
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: /dev/nginx
        awslogs-region: us-east-1
        awslogs-stream: nginx-logs
